### ISSUE TITLE
Sequences for deploying vf-apps

### ISSUE THREAD

**Issue by bhaugen** [valueflows/vf-apps#1]
This is a discussion issue which may turn into a wiki page.

Vf-apps might be deployed in different sequences for different agents and different purposes.

One sequence might be a logical progression of developing economic organizations:

1. Deploy the personal Agent apps first.
2. Then deploy the organizational-forming apps and the organizational Agent apps.
3. Then the apps that the people and organizations want to use.

Another sequence might be for a community that already exists, according to what it might find useful. For example, [Luandro of Moinho-Mesh](https://www.loomio.org/d/KEcf2u84/experimentation-with-open-app-ecosystem) thinks that the first useful apps might be a buying club like [Cobuy](https://github.com/root-systems/cobuy) or a ride-sharing app. So he would deploy those first, and then the people who wanted to use them would connect their personal agent apps.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-apps/-/issues/1.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
