### ISSUE TITLE
Deletable logic

### ISSUE THREAD

**Issue by bhaugen** [valueflows/vf-apps#3]
This will be a _first draft_ of some rules for when we could and when we should not delete something. The rules are stated in terms of relationships or references to the candidate for deletion. In most cases, do not delete if any other references to the candidate. In some cases, cascade or consider a [tombstone](https://en.wikipedia.org/wiki/Tombstone_(data_store)).

These considerations may vary depending on the feasibility of finding references in a particular technical environment. If finding references is difficult, consider leaving a tombstone. Given that we are targeting distributed environments, a tombstone might be the best bet in all cases. 

If we opt for tombstones in all cases, "delete" means "leave a tombstone".

* Agent:
    * do not delete if:
        * any EconomicEvents or
        * any Commitments
        * any Intents
    * cascade (also delete) other references?
        * or consider a tombstone?
* ResourceSpecification:
    * do not delete if:
        * any RecipeResources
        * any Intents
        * any EconomicResources
        * any EconomicEvents
        * any Commitments
        * any Claims
* RecipeResource:
    * do not delete if any RecipeFlows
* ProcessSpecification:
    * do not delete if: 
        * any Processes
        * any RecipeProcesses
* Process:
    * do not delete if:
        * any EconomicEvents or
        * any Commitments
        * any Intents
* Plan or Scenario:
    * do not delete if:
        * any non-deletable Processes
        * any non-deletable Commitments
    * otherwise consider cascading (deleting) associated Processes and Commitments?
* Action:
    * do not delete if:
        * any EconomicEvents
        * any Commitments
        * any Claims
        * any Intents
* Intent:
    * do not delete if:
        * any Satisfactions
* EconomicResource:
    * do not delete if any EconomicEvents
    * will a tombstone suffice for other references?

I think EconomicEvents and Claims are not deletable at all.

RecipeProcesses and RecipeFlows seem to be deletable at-will. Maybe also Proposals?

@fosterlynn  what did I miss?

**Comment by bhaugen** [comment]
What are the implications of leaving tombstones in place of "deleted" whatevers?
* Tombstones should be omitted from query results, lists of references, etc.
* what else?

**Comment by fosterlynn** [comment]
I updated a few missing things from @bhaugen 's spec, mostly to add Intents where applicable.

Also some discussion:

>Agent: 

I would also think we shouldn't delete if there are any agent relationships.  Those can be explicitly deleted first.  I'm not sure though in a distributed agent-centric environment how all records related to an agent could be found?  So maybe this depends on where the record resides?  We should also study the details of the EU requirements for removing personal data if requested by the person.  But I don't think we should cascade an agent "deletion".  And records that involve other agents (like a transfer) should still be able to know the other agent involved.

>ResourceSpecification:

This is another one where we would need access to all the possible distributed places that could have used the resource specification.

>Plan or Scenario: consider cascading (deleting) associated Processes and Commitments?

I think Plan and Scenario should cascade if all the associated processes and commitments are deletable.  This is useful when generating plans from recipe, and doing some experimentation or testing.

>Action:

I don't think actions should be deletable.  They are basically hard-coded.

>EconomicResource:

Won't there always be an EconomicEvent?  How about something like the creating economic event (if it is the only one) and the resource can be deleted at the same time if there are no other references (commitments, intents)?

**Comment by pospi** [comment]
This is a fantastic starting point. Thanks heaps (:

> Tombstones should be omitted from query results, lists of references, etc.
>
> What are the implications of leaving tombstones in place of "deleted" whatevers?

I actually think this ends up being a human protocol dependent on the purpose of the network. It's an agreement about what is "polite" in distributed environments. It's not "polite" to peer into people's windows; but it's also not "polite" in many postcapitalist economic networks to make past versions of the truth inaccessible. And the waters are muddied further when you consider deletion of things that have not yet been viewed or linked to by other content- does it matter? Is there a time period where deletion is acceptable, after which it should not be?

So I propose that (in the Holochain implementation, at least) we make access to archival versions a configurable option (which could be implemented via a generic zome trait). I find it a problematic ideological line to walk; because actually this is an act of disempowering non-technical people (people with the skills can still look into their source chain database to read ommitted entries directly). But the presumption in eco-networks (as opposed to [ego-networks](https://medium.com/virtual-teams-for-systemic-change/network-ing-does-not-equal-network-weaving-abf1978e79c)) would be that technical participants are being "polite" and abiding by the rules as well as those viewing the system through the UI layer.

> How about something like the creating economic event (if it is the only one) and the resource can be deleted at the same time if there are no other references (commitments, intents)?

Perfect. That's what I was expecting to hear!

**Comment by pospi** [comment]
It seems as though the general-purpose answer to these may be that more or less nothing can be deleted if any links still remain pointing to it- is that the case? And is it also the case that records may be deleted once all records linking to them have also been deleted (or tombstoned)?

If yes, I'd like to offer that `Intent` not be deletable if referenced by any `ProposedIntents`.

**Comment by bhaugen** [comment]
> It seems as though the general-purpose answer to these may be that more or less nothing can be deleted if any links still remain pointing to it- is that the case? And is it also the case that records may be deleted once all records linking to them have also been deleted (or tombstoned)?
> 
> If yes, I'd like to offer that `Intent` not be deletable if referenced by any `ProposedIntents`.

Those seem like good general rules.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-apps/-/issues/3.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
