### ISSUE TITLE
EconomicEvent and EconomicResource create and update

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/vf-apps#4]
Experimenting with some pseudo-code, please improve as needed.  @pospi @ivanminutillo @bhaugen 

EconomicEvent which creates an EconomicResource:

```
If action.resourceEffect is "+" or "-"
    If create-resource flag is set
        Create the resource with zero quantity fields
    Else
        If it exists
            Get the resource based on resourceInventoriedAs
    If there is a resource from the above
        If action.resourceEffect is "+"
            Add event resourceQuantity to both accountingQuantity and onhandQuantity
        Else if action.resourceEffect is "-"
            Subtract event resourceQuantity from both accountingQuantity and onhandQuantity
Else if action.resourceEffect is "-+" (two resources can be affected)
    If create-resource flag is set
        Create the to-resource with zero quantity fields
    Else
        Get the to-resource based on toResourceInventoriedAs  
    If it exists in the event
        Get the from-resource based on the resourceInventoriedAs  
    If action is "transfer-custody" or "transfer-complete" or "move"
        If the from-resource exists
            Subtract event resourceQuantity from from-resource.onhandQuantity
        If the to-resource exists
            Add event resourceQuantity to to-resource.onhandQuantity
    Else if action is "transfer-all-rights" or "transfer-complete" or "move"
        If the from-resource exists
            Subtract event resourceQuantity from from-resource.accountingQuantity
        If the to-resource exists
            Add event resourceQuantity to to-resource.accountingQuantity
```

**Comment by bhaugen** [comment]
One interesting side effect of the pseudocode below is that in the place I
marked, the result will be a resource with negative quantities.

This not necessarily wrong. Mutual credit accounts are allowed to have
negative balances, and timings of event recording can cause temporary
negative balances that can return to positive with subsequent events.

But it's something to think about.


On Wed, Sep 18, 2019 at 4:26 PM Lynn Foster <notifications@github.com>
wrote:

> Experimenting with some pseudo-code, please improve as needed. @pospi
> <https://github.com/pospi> @ivanminutillo
> <https://github.com/ivanminutillo> @bhaugen <https://github.com/bhaugen>
>
> EconomicEvent which creates an EconomicResource:
>
> If action.inventoryEffect is "+" or "-"
>     If create-resource flag is set
>         Create the resource with zero quantity fields
>     Else
>         If it exists
>             Get the resource based on resourceInventoriedAs
>     If there is a resource from the above
>         If action.inventoryEffect is "+"
>             Add event resourceQuantity to both accountingQuantity and onhandQuantity
>         Else if action.inventoryEffect is "-"
>             Subtract event resourceQuantity from both accountingQuantity and onhandQuantity
>
> If a new resource was created with zero quantity fields, these fields will
now go negative.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-apps/-/issues/4.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
