### ISSUE TITLE
link dumps

### ISSUE THREAD

**Issue by bhaugen** [valueflows/vf-apps#6]
https://spderosso.github.io/onward19.pdf

> A new approach to web application development is presented, in which an application is constructed by configuring and composing concepts drawn from a catalog developed by
experts.
> A concept is a self-contained, reusable increment of functionality. Each concept includes both front-end and back-end functionality, and exports a collection of components—fullstack GUI elements, backed by application logic and database storage.
> To build an app, the developer imports concepts from the catalog, tunes them to fit the application’s particular needs via configuration variables, and links concept components
together to create pages. Components of different concepts may be executed independently, or bound together declaratively with dataflows and synchronization. The instantiation, configuration, linking and binding of components is all expressed in a simple template language that extends HTML

@pospi how does this relate to your plans for https://github.com/valueflows/vf-ui components?

**Comment by pospi** [comment]
Interesting, but feels "heavier". The implication I get in reading that is that componentisation and modularity stops at the "concept" level- I am aiming for componets to be modular at a sub-component level. Haven't thought of many cases other than dynamic block content where that might have specific reason to exist; but broadly what I don't want is customisation that looks like "I can put a chat box here and a task board here". What we want is, "I don't like the way the chat box looks but I can pull in these other user badges instead" or "I like the way the chat box looks so I'm going to use it to represent a stream of supply chain events".

A bit hard to convey that... does it make sense?

**Comment by fosterlynn** [comment]
>A bit hard to convey that... does it make sense?

Makes sense to me (in general, haven't looked into the Declarative Assembly stuff). :+1:

**Comment by bhaugen** [comment]
Makes sense to me, too, in general. I thought it was close enuf to be interesting, and as they say, if you want a good answer on the internet, post a bad answer....

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-apps/-/issues/6.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
