### ISSUE TITLE
Fields for fulltext indexing

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-apps#7]
We need to define the set of fields which should be processed through a fulltext search indexing pipeline in order for implementations to provide such functionality.

This is less relevant in RDF, where the "client" app crawls the web to retrieve all data prior to query execution. In actual client/server or distributed implementations, the search lookups need to be performed from the "server" side of the relationship.

As a base, `skos:note` and any `vf:name` fields should be included. We need to detail any record-specific fields that need to be indexed in addition to these.

**Comment by fosterlynn** [comment]
>As a base, skos:note and any vf:name fields should be included. We need to detail any record-specific fields that need to be indexed in addition to these.

Those seem like a good start.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-apps/-/issues/7.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
